theme: jekyll-theme-minimal

title: Rintaro Yanagi
description: Researcher, <br> Computer Vision Research Team, <br> Artificial Intelligence Research Center, <br>National Institute of Advanced Industrial Science and Technology (AIST) <br>
logo: /assets/ryanagi.jpg

