theme: jekyll-theme-minimal

title: Yue Qiu
description: Researcher, <br> Computer Vision Research Team, <br> Artificial Intelligence Research Center, <br>National Institute of Advanced Industrial Science and Technology (AIST) <br>
logo: /assets/qiuyue_2018.jpg

